export const TMDB_DETAIL_CLEAR = 'TMDB_DETAIL_CLEAR';
export const TMDB_DETAIL_GET = 'TMDB_DETAIL_GET';
export const TMDB_DETAIL_SAVE = 'TMDB_DETAIL_SAVE';

export const TMDB_DISCOVER_GET = 'TMDB_DISCOVER_GET';

export const TMDB_BACKDROP_SET = 'TMDB_BACKDROP_SET';

export const TMDB_INIT = 'TMDB_INIT';

export const TMDB_LIST_ADD = 'TMDB_LIST_ADD';
export const TMDB_LIST_CLEAR = 'TMDB_LIST_CLEAR';
export const TMDB_LIST_SAVE = 'TMDB_LIST_SAVE';

export const TMDB_PAGE_SET = 'TMDB_PAGE_SET';

export const TMDB_SEARCH_GET = 'TMDB_SEARCH_GET';

export const TMDB_QUERY_CHANGE = 'TMDB_QUERY_CHANGE';
